// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVPpP9RvW55OM02Rr3UtYr_2794Yg5NtI',
    appId: '1:1053103180212:web:805008bff34055d29c8ae1',
    messagingSenderId: '1053103180212',
    projectId: 'upbus-f5030',
    authDomain: 'upbus-f5030.firebaseapp.com',
    databaseURL:
        'https://upbus-f5030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upbus-f5030.firebasestorage.app',
    measurementId: 'G-JSTWCNZ6FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOWItBo8D4Fl2GFm8N2zfizaPt7nxbGU',
    appId: '1:1053103180212:android:2ab9899545ad95fc9c8ae1',
    messagingSenderId: '1053103180212',
    projectId: 'upbus-f5030',
    databaseURL:
        'https://upbus-f5030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upbus-f5030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPvi3gaQUwk-wsXzTeIhv8OknzH4qLSE',
    appId: '1:1053103180212:ios:737ffaac198901b29c8ae1',
    messagingSenderId: '1053103180212',
    projectId: 'upbus-f5030',
    databaseURL:
        'https://upbus-f5030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upbus-f5030.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPvi3gaQUwk-wsXzTeIhv8OknzH4qLSE',
    appId: '1:1053103180212:ios:737ffaac198901b29c8ae1',
    messagingSenderId: '1053103180212',
    projectId: 'upbus-f5030',
    databaseURL:
        'https://upbus-f5030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upbus-f5030.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVPpP9RvW55OM02Rr3UtYr_2794Yg5NtI',
    appId: '1:1053103180212:web:533649ebf8e3b9ab9c8ae1',
    messagingSenderId: '1053103180212',
    projectId: 'upbus-f5030',
    authDomain: 'upbus-f5030.firebaseapp.com',
    databaseURL:
        'https://upbus-f5030-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upbus-f5030.firebasestorage.app',
    measurementId: 'G-YZRX4Q2DCM',
  );
}
